apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hostname.fullname" . }}
  labels:
    {{- include "node-hostname.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "node-hostname.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

